let arrOfAny: any[] = [354, -747, 0, 5.986, -7.418, 'King', 'Привіт', 'Ukraine', true, false];
console.log(arrOfAny[0]);
console.log(arrOfAny[1]);
console.log(arrOfAny[2]);
console.log(arrOfAny[3]);
console.log(arrOfAny[4]);
console.log(arrOfAny[5]);
console.log(arrOfAny[6]);
console.log(arrOfAny[7]);
console.log(arrOfAny[8]);
console.log(arrOfAny[9]);